name: datasetsforecast
channels:
  - conda-forge
dependencies:
  - aiohttp
  - jupyterlab
  - numba
  - numpy
  - scikit-learn  
  - pandas
  - pip
  - requests
  - tqdm
  - xlrd>=1.0.0
  - pip:
    - nbdev
    - utilsforecast>=0.0.8
