name: datasetsforecast
channels:
  - conda-forge
dependencies:
  - aiohttp
  - jupyterlab
  - numba
  - numpy
  - pandas
  - pip
  - requests
  - tqdm
  - xlrd>=1.0.0
  - fugue
  - pip:
    - nbdev
    - fugue[dask,ray]>=0.8.1
