# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://Nixtla.github.io/datasetsforecast/"

git_url = "https://github.com/Nixtla/statsforecast/tree/main/"

def custom_doc_links(name): return None
