name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Clone repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up environment
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # 5.3.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pip requirements
        run: pip install uv && uv pip install --system ".[dev]"

      - name: Run tests (windows)
        if: ${{ matrix.os == 'windows-latest' }} # prevent m5 errors
        run: nbdev_test --n_workers 0 --do_print --skip_file_glob "*m5*"

      - name: Run tests
        if: ${{ matrix.os != 'windows-latest' }} # prevent m5 errors
        run: nbdev_test --n_workers 0 --do_print
